#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gotify"
name = "Gotify"
description.en = "Simple server for sending and receiving messages"
description.fr = "Simple serveur pour envoyer et recevoir des messages"

version = "2.8.0~ynh1"

maintainers = ["plopoyop"]

[upstream]
license = "MIT"
website = "http://gotify.net"
admindoc = "https://gotify.net/docs/index"
code = "https://github.com/gotify/server"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gotify"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    in_subdir = false
    armhf.url = "https://github.com/gotify/server/releases/download/v2.8.0/gotify-linux-arm-7.zip"
    armhf.sha256 = "adb30618cd45ad6dcb1a2f0327b4efb894ee0581a72a64894e0e2d233563a6f9"
    arm64.url = "https://github.com/gotify/server/releases/download/v2.8.0/gotify-linux-arm64.zip"
    arm64.sha256 = "08db313ec6e60611462c9b5498149c936f80768af3a035a79efe8aa26a27850b"
    amd64.url = "https://github.com/gotify/server/releases/download/v2.8.0/gotify-linux-amd64.zip"
    amd64.sha256 = "4e2bbbd8460930aefb8ed2e40bf6890ab5462f8d9d25d0529f1fa7e2bf60b9bd"
    i386.url = "https://github.com/gotify/server/releases/download/v2.8.0/gotify-linux-386.zip"
    i386.sha256 = "91df2f52dcab84351e3b15ffad51bbebfc1c5c65d10a83e6938e1b9ea150d38a"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.armhf = "gotify-linux-arm-7.zip"
    autoupdate.asset.arm64 = "gotify-linux-arm64.zip"
    autoupdate.asset.amd64 = "gotify-linux-amd64.zip"
    autoupdate.asset.i386 = "gotify-linux-386.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["images", "plugins"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
