packaging_format = 2

id = "gotify"
name = "Gotify"
description.en = "Simple server for sending and receiving messages"
description.fr = "Simple serveur pour envoyer et recevoir des messages"

version = "2.6.3~ynh1"

maintainers = ["plopoyop"]

[upstream]
license = "MIT"
website = "http://gotify.net"
admindoc = "https://gotify.net/docs/index"
code = "https://github.com/gotify/server"

[integration]
yunohost = ">= 12.0"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gotify"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        armhf.url = "https://github.com/gotify/server/releases/download/v2.6.3/gotify-linux-arm-7.zip"
        armhf.sha256 = "38b2cfb28f5985da258a7373310585122584460c2e411bd8356d0d8d1179ccc3"
        arm64.url = "https://github.com/gotify/server/releases/download/v2.6.3/gotify-linux-arm64.zip"
        arm64.sha256 = "c4fa97b18508b47fc13be180ac194e7b7699bdb56976831206af252cda28b1c1"
        amd64.url = "https://github.com/gotify/server/releases/download/v2.6.3/gotify-linux-amd64.zip"
        amd64.sha256 = "14e4ba3c8e50c988ad350be90d1fa8ea60b34ca827935123373e47faf38de3c3"
        i386.url = "https://github.com/gotify/server/releases/download/v2.6.3/gotify-linux-386.zip"
        i386.sha256 = "5b761717d324f49360735534d8f2609051b4a3afe0f6769dfbddf77c28ab02ba"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.armhf = "gotify-linux-arm-7.zip"
        autoupdate.asset.arm64 = "gotify-linux-arm64.zip"
        autoupdate.asset.amd64 = "gotify-linux-amd64.zip"
        autoupdate.asset.i386 = "gotify-linux-386.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["images", "plugins"]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
