packaging_format = 2

id = "gotify"
name = "Gotify"
description.en = "Simple server for sending and receiving messages"
description.fr = "Simple serveur pour envoyer et recevoir des messages"

version = "2.3.0~ynh1"

maintainers = ["plopoyop"]

[upstream]
license = "MIT"
website = "http://gotify.net"
admindoc = "https://gotify.net/docs/index"
code = "https://github.com/gotify/server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gotify"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        armhf.url = "https://github.com/gotify/server/releases/download/v2.3.0/gotify-linux-arm-7.zip"
        armhf.sha256 = "510030433d27fb11566f7f26c2159a70a35deddc6a595be5a802467dc7408f26"
        arm64.url = "https://github.com/gotify/server/releases/download/v2.3.0/gotify-linux-arm64.zip"
        arm64.sha256 = "dc7caac45fbc4e3ab189e72b3a6d56890b4c16a341cca4f3de9a706c8b96c42c"
        amd64.url = "https://github.com/gotify/server/releases/download/v2.3.0/gotify-linux-amd64.zip"
        amd64.sha256 = "53ebd14063c36aba91844e9a7671a51b14878b4a1d8599c92dd8dbcc8e7d4527"
        i386.url = "https://github.com/gotify/server/releases/download/v2.3.0/gotify-linux-386.zip"
        i386.sha256 = "99db17eec0a1fa0a12ff3df463d77078a5114a57dbe1559e7a31e4c428ebe084"
        rename = "gotify"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["images", "plugins"]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
   packages = "mariadb-server"

    [resources.database]
    type = "mysql"
