#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gotify"
name = "Gotify"
description.en = "Simple server for sending and receiving messages"
description.fr = "Simple serveur pour envoyer et recevoir des messages"

version = "2.9.0~ynh1"

maintainers = ["plopoyop"]

[upstream]
license = "MIT"
website = "http://gotify.net"
admindoc = "https://gotify.net/docs/index"
code = "https://github.com/gotify/server"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gotify"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    in_subdir = false
    armhf.url = "https://github.com/gotify/server/releases/download/v2.9.0/gotify-linux-arm-7.zip"
    armhf.sha256 = "9967f2a6cef9885c3adff59c0bc5d5d4b0056c50664858907d704623a145c100"
    arm64.url = "https://github.com/gotify/server/releases/download/v2.9.0/gotify-linux-arm64.zip"
    arm64.sha256 = "c57f40f2ed8b0c39daf2055a5718b86199b77d1a783979313972e4485a044400"
    amd64.url = "https://github.com/gotify/server/releases/download/v2.9.0/gotify-linux-amd64.zip"
    amd64.sha256 = "c2650509a3a989937154b216eae4d160e38ba20c224f3212eb351d337ec7c1de"
    i386.url = "https://github.com/gotify/server/releases/download/v2.9.0/gotify-linux-386.zip"
    i386.sha256 = "551f259f830b0db1d83d1c306475b5732e6f61cd771251265fc57e027dbbef22"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.armhf = "gotify-linux-arm-7.zip"
    autoupdate.asset.arm64 = "gotify-linux-arm64.zip"
    autoupdate.asset.amd64 = "gotify-linux-amd64.zip"
    autoupdate.asset.i386 = "gotify-linux-386.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["images", "plugins"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
