packaging_format = 2

id = "gotify"
name = "Gotify"
description.en = "Simple server for sending and receiving messages"
description.fr = "Simple serveur pour envoyer et recevoir des messages"

version = "2.5.0~ynh1"

maintainers = ["plopoyop"]

[upstream]
license = "MIT"
website = "http://gotify.net"
admindoc = "https://gotify.net/docs/index"
code = "https://github.com/gotify/server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gotify"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        armhf.url = "https://github.com/gotify/server/releases/download/v2.5.0/gotify-linux-arm-7.zip"
        armhf.sha256 = "85017500913394421a9fa31e339327fb73cc3ee8753724cfcb95728c46de556a"
        arm64.url = "https://github.com/gotify/server/releases/download/v2.5.0/gotify-linux-arm64.zip"
        arm64.sha256 = "c84c794719d1c56fc9c1b781579ac3c5326995a201cf758ce38d5aa208e070ad"
        amd64.url = "https://github.com/gotify/server/releases/download/v2.5.0/gotify-linux-amd64.zip"
        amd64.sha256 = "6cf0fb4608f734008c42850c15248a287621b620852d91d8cec6787d1c0e7189"
        i386.url = "https://github.com/gotify/server/releases/download/v2.5.0/gotify-linux-386.zip"
        i386.sha256 = "a17340eeb95062ca39c36c1047cad16e9f97b4a33b914cef97b3bf3bff069d42"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.armhf = "gotify-linux-arm-7.zip"
        autoupdate.asset.arm64 = "gotify-linux-arm64.zip"
        autoupdate.asset.amd64 = "gotify-linux-amd64.zip"
        autoupdate.asset.i386 = "gotify-linux-386.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["images", "plugins"]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
