packaging_format = 2

id = "gotify"
name = "Gotify"
description.en = "Simple server for sending and receiving messages"
description.fr = "Simple serveur pour envoyer et recevoir des messages"

version = "2.6.0~ynh1"

maintainers = ["plopoyop"]

[upstream]
license = "MIT"
website = "http://gotify.net"
admindoc = "https://gotify.net/docs/index"
code = "https://github.com/gotify/server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gotify"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        armhf.url = "https://github.com/gotify/server/releases/download/v2.6.0/gotify-linux-arm-7.zip"
        armhf.sha256 = "8fe39d9e33cdc46c1853ba48284b6f87823b9dcc5942dbb88be8eee3492b2d6a"
        arm64.url = "https://github.com/gotify/server/releases/download/v2.6.0/gotify-linux-arm64.zip"
        arm64.sha256 = "c04bd48bdf754fe3f736010b04c2974aad0e07b89cbb6a577fd839f557a4aaff"
        amd64.url = "https://github.com/gotify/server/releases/download/v2.6.0/gotify-linux-amd64.zip"
        amd64.sha256 = "4555986a679d1b18343e429637d1cfaccf3ed94958206df069a3d01019584a32"
        i386.url = "https://github.com/gotify/server/releases/download/v2.6.0/gotify-linux-386.zip"
        i386.sha256 = "0f178301c0d08a7a85d61cf39d6ea694475546b3a0df5598ce9ee7939179ff5d"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.armhf = "gotify-linux-arm-7.zip"
        autoupdate.asset.arm64 = "gotify-linux-arm64.zip"
        autoupdate.asset.amd64 = "gotify-linux-amd64.zip"
        autoupdate.asset.i386 = "gotify-linux-386.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["images", "plugins"]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
