packaging_format = 2

id = "gotify"
name = "Gotify"
description.en = "Simple server for sending and receiving messages"
description.fr = "Simple serveur pour envoyer et recevoir des messages"

version = "2.6.1~ynh1"

maintainers = ["plopoyop"]

[upstream]
license = "MIT"
website = "http://gotify.net"
admindoc = "https://gotify.net/docs/index"
code = "https://github.com/gotify/server"

[integration]
yunohost = ">= 12.0"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gotify"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        armhf.url = "https://github.com/gotify/server/releases/download/v2.6.1/gotify-linux-arm-7.zip"
        armhf.sha256 = "43f300ae5985f2520a91b437925141a925356fa3074f075d4e9b7fe9fdfffd1b"
        arm64.url = "https://github.com/gotify/server/releases/download/v2.6.1/gotify-linux-arm64.zip"
        arm64.sha256 = "1e333b1b2bdb7d9c7c128819331132d023808352684129e43d2d338368a848b7"
        amd64.url = "https://github.com/gotify/server/releases/download/v2.6.1/gotify-linux-amd64.zip"
        amd64.sha256 = "77c90e271011d0a9f9024b0f869d0e044d886593639b5884050de0073739fab3"
        i386.url = "https://github.com/gotify/server/releases/download/v2.6.1/gotify-linux-386.zip"
        i386.sha256 = "c16993051294701a71933859b1b4512e9095d95edbf1bce43e69115f6f08353b"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.armhf = "gotify-linux-arm-7.zip"
        autoupdate.asset.arm64 = "gotify-linux-arm64.zip"
        autoupdate.asset.amd64 = "gotify-linux-amd64.zip"
        autoupdate.asset.i386 = "gotify-linux-386.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["images", "plugins"]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
