server:
  port: __PORT__ # the port the HTTP server will listen on
  listenaddr: 127.0.0.1 # only listen for connections from local reverse proxy

  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: false # redirect to https if site is accessed by http

  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
      - ".+.__DOMAIN__"

database: # for database see (configure database section)
  dialect: mysql
  connection: __DB_USER__:__DB_PWD__@unix(/var/run/mysqld/mysqld.sock)/__DB_NAME__?charset=utf8&parseTime=True&loc=Local

defaultuser: # on database creation, gotify creates an admin user
  name: __ADMIN__ # the username of the default user
  pass: __PASSWORD__ # the password of the default user
passstrength: 12 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: __DATA_DIR__/images # the directory for storing uploaded images
pluginsdir: __DATA_DIR__/plugins # the directory where plugin resides
